server:
  port: 8080
spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false
    servlet:
      content-type: text/html
  datasource:
    username: filesys
    password: filesys
    url: jdbc:mysql://localhost:3306/filesys?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: top.jaign.filesys.entity
logging:
  level:
    top:
      jaign:
        filesys:
          mapper: debug
